import numpy as np

from segfix import io, operations as ops
from segfix.model import UNASSIGNED


def _write_raycloud_ply(path, xyz, rgb):
    """Hand-write a tiny binary raycloud-style PLY (double xyz, normals, rgba)."""
    n = len(xyz)
    dtype = np.dtype([
        ("x", "<f8"), ("y", "<f8"), ("z", "<f8"), ("time", "<f8"),
        ("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4"),
        ("red", "u1"), ("green", "u1"), ("blue", "u1"), ("alpha", "u1"),
    ])
    arr = np.zeros(n, dtype=dtype)
    arr["x"], arr["y"], arr["z"] = xyz[:, 0], xyz[:, 1], xyz[:, 2]
    arr["time"] = np.arange(n)
    arr["nz"] = 1.0
    arr["red"], arr["green"], arr["blue"] = rgb[:, 0], rgb[:, 1], rgb[:, 2]
    arr["alpha"] = 255
    header = (
        "ply\nformat binary_little_endian 1.0\n"
        "comment generated by raycloudtools library\n"
        f"element vertex {n}\n"
        "property double x\nproperty double y\nproperty double z\n"
        "property double time\n"
        "property float nx\nproperty float ny\nproperty float nz\n"
        "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        "property uchar alpha\nend_header\n"
    ).encode("ascii")
    with open(path, "wb") as f:
        f.write(header)
        f.write(arr.tobytes())


def test_load_rgb_segmented_groups_by_colour(tmp_path):
    # 3 trees by colour + a black (unsegmented) group
    colours = np.array([[200, 0, 0], [0, 200, 0], [0, 0, 200], [0, 0, 0]])
    xyz = np.random.RandomState(0).rand(40, 3)
    rgb = np.repeat(colours, 10, axis=0).astype(np.uint8)
    path = tmp_path / "seg.ply"
    _write_raycloud_ply(path, xyz, rgb)

    cloud = io.load(str(path))
    assert cloud.source_format == "raycloud_rgb"
    # three coloured trees, black mapped to unassigned
    assert len(cloud.tree_ids) == 3
    assert (cloud.labels == UNASSIGNED).sum() == 10
    # each colour forms one contiguous label group
    assert {tuple(c) for c in cloud.label_colors.values()} == {
        (200, 0, 0), (0, 200, 0), (0, 0, 200)
    }
    assert set(cloud.attributes) >= {"time", "nx", "ny", "nz", "alpha"}


def test_rgb_segmented_roundtrip_recolours(tmp_path):
    colours = np.array([[200, 0, 0], [0, 200, 0]])
    xyz = np.random.RandomState(1).rand(20, 3)
    rgb = np.repeat(colours, 10, axis=0).astype(np.uint8)
    path = tmp_path / "seg.ply"
    _write_raycloud_ply(path, xyz, rgb)

    cloud = io.load(str(path))
    t_a, t_b = sorted(cloud.tree_ids.tolist())
    survivor_colour = cloud.label_colors[t_a]  # tree A keeps its colour
    # move tree B's points into tree A
    ops.reassign(cloud, np.flatnonzero(cloud.labels == t_b), t_a)

    out = tmp_path / "fixed.ply"
    io.save(cloud, str(out))
    reloaded = io.load(str(out))

    assert reloaded.n_points == 20
    # everything is now one colour (tree A's), so a single tree remains
    assert len(reloaded.tree_ids) == 1
    assert set(reloaded.label_colors.values()) == {survivor_colour}
